# Generated by Django 3.0.10 on 2020-10-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='The owner has passed away', max_length=10)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Software Developer', 'Software Developer'), ('Engineer', 'Engineer'), ('Nail Master', 'Nail Master'), ('Vlogger', 'Vlogger'), ('Vtuber', 'Vtuber')], default='The owner has too much money', max_length=20)),
                ('name', models.CharField(default='GivesMeConniptions', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('Uptown', 'Uptown'), ('Downtown', 'Downtown'), ('Center', 'Center'), ('Industrial', 'Industrial')], default="My uncles' basement", max_length=15)),
                ('capacity', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField()),
                ('farm_owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shelters', to='api.HomeOwner')),
            ],
        ),
        migrations.CreateModel(
            name='CatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Hermaphrodites', max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('colour', models.CharField(choices=[('White', 'White'), ('Redhead', 'Redhead'), ('Black', 'Black'), ('Brown', 'Brown')], default='Ethereal', max_length=10)),
                ('farm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cats', to='api.Farm')),
            ],
        ),
    ]
