# Generated by Django 3.0.10 on 2020-10-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_simplefarm_farm_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleFarm',
        ),
    ]
